FROM node:18-slim
RUN apt-get update && \
    apt-get install -y android-tools-adb curl python3 make g++ && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . .
RUN npm install --omit=dev --no-audit --no-fund
EXPOSE 8000
CMD ["npm", "start"]
